# Generated by Django 2.2.9 on 2021-08-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210822_2220'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='News',
        ),
    ]
